sudo: false
dist: xenial
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
language: ruby
cache: bundler

services:
  - postgresql

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

before_script:
  - psql -c 'create database "webauthn-app_test";' -U postgres

script:
  - bundle exec rake
  - bundle exec rake test:system
