sudo: false
dist: xenial
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
language: ruby
cache: bundler

services:
  - postgresql

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - psql -c 'create database "webauthn-app_test";' -U postgres

script:
  - bundle exec rake
  - bundle exec rake test:system
