sudo: false
dist: xenial
language: ruby
cache: bundler

services:
  - postgresql

before_script:
  - psql -c 'create database "webauthn-app_test";' -U postgres

script:
  - bundle exec rake
  - bundle exec rake test:system
